name: ci-testv

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Run PostgreSQL
        run: |
          make postgres || make startdb

      - name: Wait for PostgreSQL
        run: |
          timeout 30 bash -c 'until docker exec some-postgres pg_isready -U root; do sleep 1; done'

      - name: Create database
        run: |
          make createdb-ci || echo "Database may already exist"

      - name: Install golang migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.19.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/migrate
          which migrate

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test
